MODULE_NAME = "simplecfg"
MODULE_NAME_FULL = "Simple CFG"
MODULE_VERSION = "indev0.1"
MODULE_AUTHOR = "Max Loiacono"
MODULE_DESCRIPTION = "A library to easily manage program configuration."
MODULE_URL = "https://github.com/itsmaxymoo/simplecfg"
